export const defaultValues = {
  name: "",
  origin: "",
  pushForce: "",
  weight: "",
  height: "",
  typeLoad: "",
  dateActivity: "",
  active: false,
  typeOil: "",
  spaceZone: "",
  levelPower: "",
  typeSpaceship: "",
  loadCapacity: "",
  missionType: "",
  engineNumbers: "",
  orbitSpeed: "",
};

export const valuesInput = [
  { label: "Nombre", value: "name" },
  { label: "Origen", value: "origin" },
  { label: "Fuerza de empuje", value: "pushForce" },
  { label: "Peso", value: "weight" },
  { label: "Altura", value: "height" },
  { label: "Tipo de carga", value: "typeLoad" },
  { label: "Fecha de actividad", value: "dateActivity" },
  { label: "tipo de combustible", value: "typeOil" },
  { label: "Zona espacial", value: "spaceZone" },
  { label: "Tipo de nave", value: "typeSpaceship" },
  { label: "Nivel de poder", value: "levelPower" },
  { label: "Capacidad de carga", value: "loadCapacity" },
  { label: "Typo de mision", value: "missionType" },
  { label: "Cantidad de motores", value: "engineNumbers" },
  { label: "Velicidad de orbita", value: "orbitSpeed" },
];
